version: "3"

services:
  ghost:
    image: ghost
    container_name: basti-blog
    volumes: 
      - ./docker-mount:/var/lib/ghost/content/themes/basti-blog:rw,z
    ports: 
      - "9090:2368"
    environment:
      - url=http://localhost:9090
      - NODE_ENV=development

