version: "3"

services:
  ghost:
    image: ghost
    container_name: your-theme-name
    volumes: 
      - ./docker-mount:/var/lib/ghost/content/themes/your-theme-name:rw,z
    ports: 
      - "9090:2368"
    environment:
      - url=http://localhost:9090
      - NODE_ENV=development
    restart: "no"

